name: preconnect
description: "Your personalised student portal for BRAC University"
publish_to: 'none'

version: 1.3.9+20260233

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^10.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  http: ^1.6.0
  webview_flutter_android: ^4.10.11
  webview_windows: ^0.2.2
  webview_flutter_wkwebview: ^3.9.5
  connectivity_plus: ^7.0.0
  webview_flutter: ^4.13.1
  intl: ^0.20.2
  android_intent_plus: ^6.0.0
  qr: ^3.0.2
  mobile_scanner: ^7.1.4
  archive: ^4.0.7
  flutter_alarmkit: ^0.0.10
  flutter_local_notifications: ^20.0.0
  barcode_widget: ^2.0.4
  flutter_flip_card: ^0.0.6
  flutter_svg: ^2.0.10
  timezone: ^0.10.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  in_app_update: ^4.2.5
  package_info_plus: ^8.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#EAF4FF"
  color_dark: "#000000"
  image: "web/icons/Icon-512.png"
  image_dark: "web/icons/Icon-512.png"
  android: true
  ios: true
  web: false
  android_12:
    color: "#EAF4FF"
    color_dark: "#000000"
    image: "web/icons/Icon-512.png"
    image_dark: "web/icons/Icon-512.png"


flutter:

  uses-material-design: true
  assets:
    - assets/bracu.svg
